from datetime import datetime
from app import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    uploads = db.relationship('Upload', backref='user', lazy=True)
    trades = db.relationship('Trade', backref='user', lazy=True)
    open_trades = db.relationship('OpenTrade', backref='user', lazy=True)

class Upload(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    file_name = db.Column(db.String(100), nullable=False)
    file_path = db.Column(db.String(200), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    upload_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class Trade(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Closing_Ref = db.Column(db.String(100), nullable=False)
    Closed = db.Column(db.DateTime, nullable=False)
    Opening_Ref = db.Column(db.String(100), nullable=False)
    Opened = db.Column(db.DateTime, nullable=False)
    Market = db.Column(db.String(100), nullable=False)
    Period = db.Column(db.String(100), nullable=False)
    Direction = db.Column(db.String(10), nullable=False)
    Size = db.Column(db.Float, nullable=False)
    Opening = db.Column(db.Float, nullable=False)
    Closing = db.Column(db.Float, nullable=False)
    Trade_Ccy = db.Column(db.String(10), nullable=False)
    Total = db.Column(db.Float, nullable=False)
    Funding = db.Column(db.Float, nullable=False)
    Borrowing = db.Column(db.Float, nullable=False)
    Dividends = db.Column(db.Float, nullable=False)
    LR_Prem = db.Column(db.Float, nullable=False)
    Others = db.Column(db.Float, nullable=False)
    Comm_Ccy = db.Column(db.String(10), nullable=False)
    Commissions = db.Column(db.Float, nullable=False)
    PL = db.Column(db.Float, nullable=False)
    setup_type = db.Column(db.String(100), nullable=False)
    note = db.Column(db.String(200), nullable=False)
    PL_percent = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

class OpenTrade(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    Opening_Ref = db.Column(db.String(100), nullable=False)
    Opened = db.Column(db.DateTime, nullable=False)
    Market = db.Column(db.String(100), nullable=False)
    Period = db.Column(db.String(100), nullable=False)
    Direction = db.Column(db.String(10), nullable=False)
    Size = db.Column(db.Float, nullable=False)
    Opening = db.Column(db.Float, nullable=False)
    Stop_Loss = db.Column(db.Float, nullable=False)
    Trade_Ccy = db.Column(db.String(10), nullable=False)
    Funding = db.Column(db.Float, nullable=False)
    Borrowing = db.Column(db.Float, nullable=False)
    Dividends = db.Column(db.Float, nullable=False)
    LR_Prem = db.Column(db.Float, nullable=False)
    Others = db.Column(db.Float, nullable=False)
    Comm_Ccy = db.Column(db.String(10), nullable=False)
    Commissions = db.Column(db.Float, nullable=False)
    potential_loss_percentage = db.Column(db.Float, nullable=False)
    last_price = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
