"""Add journal customization and entry models

Revision ID: 9793b0aea837
Revises: 2d33c173fa28
Create Date: 2024-07-31 11:22:48.395971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9793b0aea837'
down_revision = '2d33c173fa28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_customization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.String(length=20), nullable=False),
    sa.Column('entry_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('open_trades')
    op.drop_table('trades')
    op.drop_table('file_paths')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_paths',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('trades',
    sa.Column('Closing_Ref', sa.TEXT(), nullable=True),
    sa.Column('Closed', sa.DATE(), nullable=True),
    sa.Column('Opening_Ref', sa.TEXT(), nullable=True),
    sa.Column('Opened', sa.TEXT(), nullable=True),
    sa.Column('Market', sa.TEXT(), nullable=True),
    sa.Column('Period', sa.TEXT(), nullable=True),
    sa.Column('Direction', sa.TEXT(), nullable=True),
    sa.Column('Size', sa.REAL(), nullable=True),
    sa.Column('Opening', sa.REAL(), nullable=True),
    sa.Column('Closing', sa.REAL(), nullable=True),
    sa.Column('Trade_Ccy', sa.TEXT(), nullable=True),
    sa.Column('PL', sa.REAL(), nullable=True),
    sa.Column('Funding', sa.REAL(), nullable=True),
    sa.Column('Borrowing', sa.REAL(), nullable=True),
    sa.Column('Dividends', sa.REAL(), nullable=True),
    sa.Column('LR_Prem', sa.REAL(), nullable=True),
    sa.Column('Others', sa.REAL(), nullable=True),
    sa.Column('Comm_Ccy', sa.TEXT(), nullable=True),
    sa.Column('Comm', sa.REAL(), nullable=True),
    sa.Column('Total', sa.REAL(), nullable=True),
    sa.Column('P/L %', sa.REAL(), nullable=True),
    sa.Column('setup_type', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('Commissions', sa.REAL(), nullable=True),
    sa.Column('PL_percent', sa.TEXT(), nullable=True)
    )
    op.create_table('open_trades',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('Opening_Ref', sa.TEXT(), nullable=True),
    sa.Column('Opened', sa.TEXT(), nullable=True),
    sa.Column('Market', sa.TEXT(), nullable=True),
    sa.Column('Period', sa.TEXT(), nullable=True),
    sa.Column('Direction', sa.TEXT(), nullable=True),
    sa.Column('Size', sa.REAL(), nullable=True),
    sa.Column('Opening', sa.REAL(), nullable=True),
    sa.Column('Trade_Ccy', sa.TEXT(), nullable=True),
    sa.Column('Funding', sa.REAL(), nullable=True),
    sa.Column('Borrowing', sa.REAL(), nullable=True),
    sa.Column('Dividends', sa.REAL(), nullable=True),
    sa.Column('LR_Prem', sa.REAL(), nullable=True),
    sa.Column('Others', sa.REAL(), nullable=True),
    sa.Column('Comm_Ccy', sa.TEXT(), nullable=True),
    sa.Column('Commissions', sa.REAL(), nullable=True),
    sa.Column('setup_type', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('Stop_Loss', sa.REAL(), nullable=True),
    sa.Column('potential_loss_percentage', sa.REAL(), nullable=True),
    sa.Column('last_price', sa.TEXT(), nullable=True)
    )
    op.drop_table('upload')
    op.drop_table('journal_entry')
    op.drop_table('journal_customization')
    # ### end Alembic commands ###
